version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - app
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    networks:
      - app
    volumes:
      - redis-data:/bitnami/redis/data
networks:
  app:
    driver: bridge

volumes:
  redis-data: {}
